version: '3.8'

services:
  postgres:
    image: postgres:latest                # или latest / конкретная версия
    container_name: postgres-disser
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: disser
    ports:
      - "9543:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d   # монтируем папку со скриптами
      - pgdata:/var/lib/postgresql/data               # постоянное хранилище данных

volumes:
  pgdata: